# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'IBLSocket' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for IBLSocket
  pod 'IBLSocket',:path => '../socket'

end

target 'server' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for server

end

target 'IMClient' do
    # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
    # use_frameworks!
    
    # Pods for IBLSocket
    pod 'IBLSocket',:path => '../socket'
    
end
